<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Additional Quiz</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: Samuel Mensah
- ID: 1901213965

In [4]:
import numpy as np
import pandas as pd

<div class="alert alert-warning">
<b>QUESTION 1:</b> 
    
Please print the following string using **ONE LINE** of code:
    
```
Dear Alice,

Eve's cat has been found in hotel "Kitty".

Sincerely,
Bob
```

</div>

In [49]:
print('''Dear Alice,

Eve's cat has been found in hotel "Kitty".

Sincerely,
Bob''')

Dear Alice,

Eve's cat has been found in hotel "Kitty".

Sincerely,
Bob


<div class="alert alert-warning">
<b>QUESTION 2:</b> 
    
1, Define a string: `names = 'Olivia; Amelia; Isla; Ava; Grace'`
  
2, Split the names in the string and turn it into a list. Print the list, the expected output is:
   
`['Olivia', 'Amelia', 'Isla', 'Ava', 'Grace']`
</div>

In [2]:
names = 'Olivia; Amelia; Isla; Ava; Grace'
print(names.split(';'))


['Olivia', ' Amelia', ' Isla', ' Ava', ' Grace']


<div class="alert alert-warning">
<b>QUESTION 3:</b>

One of the activation functions used in neural network is SQNL. When SQNL is used, the following equation is applied to the input signal: 
    
$f(x) = \left\{\begin{matrix} 1 & :x>2.0\\ x-\frac{x^{2}}{4}&:0\leq x\leq 2.0 \\ x+\frac{x^{2}}{4}&:-2.0\leq x<0 \\ -1 & :x<-2.0 \end{matrix}\right.$
<br>    
Write a function called <code>SQNL</code> which takes a number as the argument. The function would **return** the result of applying the activation function.

</div>

<div class="alert alert-warning">
<b>QUESTION 4:</b>
    
Please fill the gaps in the code below so that the output of it would be `The percetage of the shares Jake holds is 9.68%.`(**DO NOT** miss the period at the end of the sentence).
    
```python
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
print('________________'.format(_________))
```
</div>

In [ ]:
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
print('________________'.format(_________))

<div class="alert alert-warning">
<b>QUESTION 5:</b>
    
1, Define a dictionary: `Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}`

2, Using **ONE LINE** of code, create a list called `share_values` which contains all the values in the dictionary `Shares`.
    
3, Print `share_values`, the expected output is: `[2359, 4032, 5538, 3200, 7239, 2007]`
</div>

In [6]:
Shares={'Jake':2359, 'Terry':4032, 'Rosa':5538, 'Amy':3200, 'Charles':7239, 'Gina':2007}
share_values = [Shares['Jake'], Shares['Terry'], Shares['Rosa'], Shares['Amy'], Shares['Charles'], Shares['Gina']]
print(share_values)

[2359, 4032, 5538, 3200, 7239, 2007]


<div class="alert alert-warning">
<b>QUESTION 6:</b>
    
Please fill the gaps in the code below so that the output of it would be `[103, 105, 107, 109]`
    
```python
nums = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
print(nums[______])
```
</div>

In [41]:
nums = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
print(nums[2:9:2])

[103, 105, 107, 109]


<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define a list: `scores = [40,69,42,68,90,73,77,22,10,63,81,58,80,55,66,39,74]`

2, Write **ONE LINE** of code to print the number of elements (in the list) that are larger than 50 and smaller than 70. The expected output is : `6`
    
<br>  
    <b>DO NOT</b> write print(6)
</div>

In [31]:
scores = [40,69,42,68,90,73,77,22,10,63,81,58,80,55,66,39,74]
count = len([i for i in scores if i > 50 and i < 70])
print ("The numbers greater than 50 and less than 70 : " + str(count))

The numbers greater than 50 and less than 70 : 6


<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
Create a list which contains numbers from 500 to 0, with an interval of 50. The list should start with 500 and end with 0.
    
Print the list, the expected output is: `[500, 450, 400, 350, 300, 250, 200, 150, 100, 50, 0]`
</div>

In [24]:
list_num = list(range(500,-1,-50))
print(list_num)

[500, 450, 400, 350, 300, 250, 200, 150, 100, 50, 0]


<div class="alert alert-warning">
<b>QUESTION 9: </b> 

1, Define a dictionary: `captials = {'China':'Peking', 'USA':'Washington', 'Russia':'Moscow', 'UK':'London', 'France':'Paris'}`

2, Change the value `Peking` to `Beijing`. Print the dictionary, the expected output is: `{'China': 'Beijing', 'USA': 'Washington', 'Russia': 'Moscow', 'UK': 'London', 'France': 'Paris'}`.

In [28]:
captials = {'China':'Peking', 'USA':'Washington', 'Russia':'Moscow', 'UK':'London','France':'Paris'}
captials.update({"China":"Beijing"})
print(captials)

{'China': 'Beijing', 'USA': 'Washington', 'Russia': 'Moscow', 'UK': 'London', 'France': 'Paris'}


<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
1, Define a list: `list_abc = ['Joe', 'Kik', 'Olo', 'Seb', Jokoj, 'MadAm', 'Yolo']`
    
2, Create a for loop that iterates through `list_abc` and prints `Not a palindrome!` if the element is not a palindrome and prints `Palindrome!` if the element is a palindrome.
    
Note: Palindrome is a word that reads the same backwords and forwards, such as *'Kik'*, *'MadAm'* or *'kayak'*.

3, The expected output is:
```
Not a palindrome!
Palindrome!
Palindrome!
Not a palindrome!
Palindrome!
Palindrome!
Not a palindrome!```
</div>

In [58]:
list_abc = ['Joe', 'Kik', 'Olo', 'Seb', 'Jokoj', 'MadAm', 'Yolo']

for word in list_abc:
    if reverse(word) == word.lower():
        print("Palindrome!")
    else:
        print("Not a Palindrome!")

NameError: name 'reverse' is not defined

<div class="alert alert-warning">
<b>QUESTION 11: </b> 

1, Define two arrays:
    
```python
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])
```
    
2, Add `arr_1` and `arr_2` element by element. Print the result, the expected output is:
    
```
[[ 3  7 11]
 [15 19 23]]```

</div>

In [7]:
arr_1 = np.array([[1, 3, 5], [7, 9, 11]])
arr_2 = np.array([[2, 4, 6], [8, 10, 12]])
print(arr_1 + arr_2)

[[ 3  7 11]
 [15 19 23]]


<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
1, Define an array: `arr = np.arange(15).reshape(3, 5)`

2, Print the array below by indexing `arr`.

```    
[[ 6  7]
 [11 12]]```

</div>

In [29]:
arr = np.arange(15).reshape(3, 5)
print(arr[1:,1:3])

[[ 6  7]
 [11 12]]


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.array([[-1, 9, 10], [3, -2, 9], [6, 2, 2]])`

2, Replace the negative numbers in `arr` with 0. Print the new array, the expected output is:

```    
[[ 0  9 10]
 [ 3  0  9]
 [ 6  2  2]]```

</div>

In [30]:
 arr = np.array([[-1, 9, 10], [3, -2, 9], [6, 2, 2]])
arr[arr < 0] = 0
print(arr)

[[ 0  9 10]
 [ 3  0  9]
 [ 6  2  2]]


<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Get the data from the last column as a one-dimensional array. Print the array, the expected output is:
```
[ 2  5  8 11 14 17 20]```

</div>

In [53]:
import numpy as np
arr = np.arange(21).reshape(7,3)


<div class="alert alert-warning">
<b>QUESTION 15:</b>
    
1, Define an array: 
```python
arr = np.array([[11,  9,  5],
                [ 2,  5,  8],
                [ 7,  5,  2],
                [10, 13,  1]])
```

2, Sort the values in each row of `arr` in ascending order. Print the new array, the expected output is:
```
[[ 5  9 11]
 [ 2  5  8]
 [ 2  5  7]
 [ 1 10 13]]```

</div>

In [48]:
arr = np.array([[11,  9,  5],
                [ 2,  5,  8],
                [ 7,  5,  2],
                [10, 13,  1]])
print(arr.sort())

None


<div class="alert alert-warning">
<b>QUESTION 16:</b>

1, Define a DataFrame called `exam_attempts`:
```python
exam_attempts  = pd.DataFrame({'NAME': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                               'ATTEMPTS': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]})
```        
   
2, Convert the column names from upper case to lower case. Display the DataFrame `exam_attempts`. The expected output would be:

<img src="//i.imgur.com/GtpPSpq.png" height="14%" width="14%">
</div>

In [56]:
exam_attempts  = pd.DataFrame({'NAME': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                               'ATTEMPTS': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]})
exam_attempts.columns=map(str.lower,exam_attempts.columns)
exam_attempts

name  attempts
0  Anastasia         1
1       Andy         3
2  Katherine         2
3      Helen         3
4      Emily         2
5    Michael         3
6    Matthew         1
7      Maria         1
8      Kevin         2
9      Jonas         1

<div class="alert alert-warning">
<b>QUESTION 17:</b>

1, Add `1` to each value in column `attempts` from DataFrame `exam_attempts`.

2, Display the **updated** DataFrame `exam_attempts`, the expected output would be:
    
<img src="//i.imgur.com/RgkRw5C.png" height="14%" width="14%">

</div>

In [44]:
exam_attempts.attempts=exam_attempts.attempts+1
exam_attempts

AttributeError: 'DataFrame' object has no attribute 'attempts'

<div class="alert alert-warning">
<b>QUESTION 18:</b>

1, Define a dataframe called `exam_score`:
    
```python
exam_score  = pd.DataFrame({'name': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                            'score': [9., 10., 6.5, np.nan, 8., 8., 5.5, np.nan, 4., 2.]})
```
        
   
2, Merge DataFrames `exam_attempts` and `exam_score` based on the values in column `name`. Assign the merged DataFrame to variable `exam_result`. Display the DataFrame `exam_result`, the expected output would be:

<img src="//i.imgur.com/fur6YEN.png" height="17%" width="17%">
</div>

In [50]:
import numpy as np
exam_score  = pd.DataFrame({'name': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                            'score': [9., 10., 6.5, np.nan, 8., 8., 5.5, np.nan, 4., 2.]})
exam_score
exam_result=pd.merge(exam_attempts,exam_score)
exam_result

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

<div class="alert alert-warning">
<b>QUESTION 19:</b>

For DataFrame `exam_result`, fill the missing values in column `score` with the mean. Display the updated DataFrame, the expected output would be:

<img src="//i.imgur.com/BnbZmI8.png" height="17%" width="17%">
</div>

In [55]:
exam_score  = pd.DataFrame({'name': ['Anastasia', 'Andy', 'Katherine', 'Helen', 'Emily', 
                                      'Michael', 'Matthew', 'Maria', 'Kevin', 'Jonas'],
                            'score': [9., 10., 6.5, np.nan, 8., 8., 5.5, np.nan, 4., 2.]})
exam_score
exam_result['score'] = exam_result['score'].fillna(exam_result['score'].mean())
exam_result

NameError: name 'exam_result' is not defined

<div class="alert alert-warning">
<b>QUESTION 20: </b> 

Display the matching rows in DataFrame `exam_result` where `name` end with `a`, the expected output would be:
    
<img src="//i.imgur.com/mIRWyLs.png" height="20%" width="20%">

</div>

In [54]:
 exam_result[exam_result['name'].str.endswith('a',-1)]
    

NameError: name 'exam_result' is not defined